export const ListStyles = {
    listContainer: () => ({
        display: 'flex',
        gap: '2rem',
    }),
    filterTab: (isShown) => ({
        width: isShown ? '30%' : '54px',
        padding: '1rem',
        height: '580px',
        backgroundColor: '#03c4a1',
        border: '0',
        color: '#242424',
        display: 'flex',
        justifyContent: 'center',
        boxSizing: 'border-box',
    }),
    FilterWrapper: () => ({
        display: 'flex',
        flexDirection: 'column',
        gap: '2rem',
    }),
    filterHideButton: () => ({
        alignSelf: 'end',
        color: '#03c4a1',
    }),
    filterShowButton: () => ({
        alignSelf: 'start',
        color: '#03c4a1',
    }),
    listFormWrapper: () => ({
        display: 'flex',
        flexDirection: 'column',
        gap: '0.5rem',
        justifyContent: 'space-between',
    }),
    listFormInput: () => ({
        width: '100%',
        color: '#03c4a1',
    }),
    listFormButtonWrapper: () => ({
        display: 'flex',
        justifyContent: 'space-evenly',
        gap: '1rem',
    }),
    listFormButton: (isSuccess) => ({
        marginTop: '1rem',
        flex: '1',
        color: isSuccess ? '#03c4a1' : '#d61c4e',
    }),
    listTable: () => ({
        flex: '1',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'start',
        gap: '1rem',
        maxHeight: '500px',
        overflow: 'auto',
    }),
    listTableItem: () => ({
        padding: '0.5rem',
        backgroundColor: '#03c4a1',
        color: '#242424',
        border: '0',
        borderRadius: '12px',
        display: 'flex',
        justifyContent: 'start',
        alignItems: 'center',
        gap: '2rem',
        marginLeft: '0.5rem',
        marginRight: '0.5rem',
    }),
    tableListItemImportant: () => ({
        flex: '1',
        fontWeight: 'bold',
    }),
    linkedinLink: () => ({
        cursor: 'pointer',
        fontWeight: 'bold',
        color: '#c62a88',
        backgroundColor: '#3b3b3b',
        padding: '.5rem',
    }),
    ListActionButtonWrapper: () => ({
        alignSelf: 'end',
        display: 'flex',
        justifyContent: 'start',
        gap: '1rem',
        alignItems: 'center',
        marginLeft: '0.5rem',
        marginRight: '0.5rem',
        marginBottom: '1rem',
    }),
    listActionButton: (isSuccess = true) => ({
        flex: '1',
        color: isSuccess ? '#03c4a1' : '#d61c4e',
        flexGrow: '0',
    }),
    listWrapper: () => ({
        flex: '1',
        padding: '1rem',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'start',
    }),
    addDisclaimer: () => ({
        color: '#F806CC',
        fontWeight: 'bold',
        letterSpacing: '0.05rem',
    }),
}
